
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer 排序节点组织
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Police 公安局组织
  # ---------------------------------------------------------------------------
  - Name: Police
    Domain: police.example.com

    # peer count
    Template:
      Count: 2
      #Hostname: peer0,peer1,peer2 and so on
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Housemng 房管局组织
  # ---------------------------------------------------------------------------
  - Name: Housemng
    Domain: housemng.example.com
    Template:
      Count: 2
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Credit 征信中心组织
  # ---------------------------------------------------------------------------
  - Name: Credit
    Domain: credit.example.com
    Template:
      Count: 2
    Users:
      Count: 1