# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      # 创世块对应的文件，不是指本地的，而是docker中的，与下面的volumes进行映射相关联
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.police.example.com:
    container_name: peer0.police.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.police.example.com
      - CORE_PEER_ADDRESS=peer0.police.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.police.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.police.example.com:7051
      - CORE_PEER_LOCALMSPID=PoliceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/police.example.com/peers/peer0.police.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.police.example.com:
    container_name: peer1.police.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.police.example.com
      - CORE_PEER_ADDRESS=peer1.police.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.police.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.police.example.com:7051
      - CORE_PEER_LOCALMSPID=PoliceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/police.example.com/peers/peer1.police.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/police.example.com/peers/peer1.police.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053

  peer0.housemng.example.com:
    container_name: peer0.housemng.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.housemng.example.com
      - CORE_PEER_ADDRESS=peer0.housemng.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.housemng.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.housemng.example.com:7051
      - CORE_PEER_LOCALMSPID=HousemngMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/housemng.example.com/peers/peer0.housemng.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/housemng.example.com/peers/peer0.housemng.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053

  peer1.housemng.example.com:
    container_name: peer1.housemng.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.housemng.example.com
      - CORE_PEER_ADDRESS=peer1.housemng.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.housemng.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.housemng.example.com:7051
      - CORE_PEER_LOCALMSPID=HousemngMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/housemng.example.com/peers/peer1.housemng.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/housemng.example.com/peers/peer1.housemng.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053

  peer0.credit.example.com:
    container_name: peer0.credit.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.credit.example.com
      - CORE_PEER_ADDRESS=peer0.credit.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.credit.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.credit.example.com:7051
      - CORE_PEER_LOCALMSPID=CreditMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/credit.example.com/peers/peer0.credit.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/credit.example.com/peers/peer0.credit.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11052:7052
      - 11053:7053

  peer1.credit.example.com:
    container_name: peer1.credit.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.credit.example.com
      - CORE_PEER_ADDRESS=peer1.credit.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.credit.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.credit.example.com:7051
      - CORE_PEER_LOCALMSPID=CreditMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/credit.example.com/peers/peer1.credit.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/credit.example.com/peers/peer1.credit.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12052:7052
      - 12053:7053